import os

MINING_REWARD = 10.0
MINING_SENDER = "BLOCKCHAIN_REWARD"
EXPECTED_MINE_TIME = 10      # seconds
RETARGET_INTERVAL = 10       # blocks
GENESIS_TIMESTAMP = 1_700_000_000.0
DEFAULT_DIFFICULTY = 3
MAX_DIFFICULTY = 6
MIN_DIFFICULTY = 1